baseURL = 'https://example.org/'
languageCode = 'de-de'
title = 'Förderverein der Nordschule Neureut e.V.'
theme = 'ananke'

[menus]
  [[menus.main]]
    name = 'Startseite'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Aktuelles'
    pageRef = '/aktuelles'
    weight = 20
  [[menus.main]]
    name = 'Über uns'
    pageRef = '/ueber-uns'
    weight = 30
  [[menus.main]]
    name = 'Kontakt'
    pageRef = '/kontakt'
    weight = 40
  [[menus.main]]
    name = 'Impressum'
    pageRef = '/impressum'
        weight = 50
    
    [markup]
      [markup.goldmark]
        [markup.goldmark.renderer]
          unsafe = true
    